import SideNavBar from '@/components/common/nav-bar';
import { Login } from '@/components/form/login';
import { Button } from '@/components/ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { Input } from '@/components/ui/input';
import { getCookies } from '@/helper/setCookies';
import {
  Badge,
  HomeIcon,
  LineChartIcon,
  Package2Icon,
  PackageIcon,
  SearchIcon,
  ShoppingCartIcon,
  UsersIcon,
} from 'lucide-react';
import { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'E-com',
  description: 'Generated by create next app',
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const token = await getCookies('token');
  if (!token) {
    return (
      <html lang='en'>
        <body className='grid min-h-screen justify-center items-center overflow-hidden admin'>
          <Login />
        </body>
      </html>
    );
  }

  return (
    <>
      <div className='grid min-h-screen overflow-hidden admin w-full  lg:grid-cols-[280px_1fr]'>
        <div className='hidden border-r bg-gray-100/40 lg:block dark:bg-gray-800/40'>
          <div className='flex flex-col gap-2'>
            <div className='flex h-[60px] items-center px-6'>
              <Link className='flex items-center gap-2 font-semibold' href='#'>
                <Package2Icon className='h-6 w-6' />
                <span className=''>E-com</span>
              </Link>
            </div>
            <div className='flex-1'>
              <nav className='grid items-start px-4 text-sm font-medium'>
                <SideNavBar/>
              </nav>
            </div>
          </div>
        </div>
        <div className='flex flex-col'>
          <header className='flex h-14 lg:h-[60px] items-center gap-4 border-b bg-gray-100/40 px-6 dark:bg-gray-800/40'>
            <Link className='lg:hidden' href='#'>
              <Package2Icon className='h-6 w-6' />
              <span className='sr-only'>Home</span>
            </Link>
            <div className='flex-1'>
              <h1 className='font-semibold text-lg'>Recent Orders</h1>
            </div>
            <div className='flex flex-1 items-center gap-4 md:ml-auto md:gap-2 lg:gap-4'>
              <form className='ml-auto flex-1 sm:flex-initial'>
                <div className='relative'>
                  <SearchIcon className='absolute left-2.5 top-2.5 h-4 w-4 text-gray-500 dark:text-gray-400' />
                  <Input
                    className='pl-8 sm:w-[300px] md:w-[200px] lg:w-[300px] bg-white'
                    placeholder='Search orders...'
                    type='search'
                  />
                </div>
              </form>
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button className='rounded-full' size='icon' variant='ghost'>
                    <img
                      alt='Avatar'
                      className='rounded-full'
                      height='32'
                      src='/placeholder.svg'
                      style={{
                        aspectRatio: '32/32',
                        objectFit: 'cover',
                      }}
                      width='32'
                    />
                    <span className='sr-only'>Toggle user menu</span>
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align='end'>
                  <DropdownMenuLabel />
                  <DropdownMenuItem>Settings</DropdownMenuItem>
                  <DropdownMenuItem>Support</DropdownMenuItem>
                  <DropdownMenuSeparator />
                  <DropdownMenuItem>Logout</DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
          </header>
          <div className='flex flex-1 flex-col gap-4 p-4 md:gap-8 md:p-6'>
            {children}
          </div>
        </div>
      </div>
    </>
  );
}
